add skip gptcommit

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,5 +1,10 @@
 #!/bin/sh
 
 ### BEGIN GPTCOMMIT HOOK ###
+if ! command -v prepare-commit-msg &> /dev/null
+then
+    echo "prepare-commit-msg not found. Skiped."
+    exit
+fi
 gptcommit prepare-commit-msg --commit-msg-file "$1" --commit-source "$2" --commit-sha "$3"
 ### END GPTCOMMIT HOOK ###
